<?php
/////////////////////////////////////////////////////////////////////////////
// Copyright (C)2005 6XGate Incorporated
//
// This file is part of Dacomasy
//
// Dacomasy is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// Dacomasy is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
/////////////////////////////////////////////////////////////////////////////
/**
 * Contains language-netural and numeric version resources.
 * 
 * @package Dacomasy
 * @subpackage Resources
 * @ignore
 * @version $SixXGate: webapps/dacomasy/www/system/res/version.info.inc,v 1.1.1.1 2005/07/21 22:57:32 matthew Exp $
 */

/**#@+ Application Version Resources */

$ApplicationVersionRes['Name'] =			'Dacomasy';
$ApplicationVersionRes['Description'] =		'Multi-purpose Database Content Management System for Websites';
$ApplicationVersionRes['Major'] =			1;
$ApplicationVersionRes['Minor'] =			0;
$ApplicationVersionRes['Build'] =			550;
$ApplicationVersionRes['Special'] =			'ALPHA';
$ApplicationVersionRes['Version'] =			$ApplicationVersionRes['Major'] . '.' . $ApplicationVersionRes['Minor'] . ' BUILD ' . $ApplicationVersionRes['Build'] . ' ' . $ApplicationVersionRes['Special'];
$ApplicationVersionRes['Company'] =			'6XGate Incorporated';
$ApplicationVersionRes['CompanyURL'] = 		'http://www.sixxgate.com/';
$ApplicationVersionRes['CopyrightDates'] =	'2005';
$ApplicationVersionRes['Copyright'] = 		'Copyright &copy;' . $ApplicationVersionRes['CopyrightDates'] . ' ' . $ApplicationVersionRes['Company'];

/**#@-*/

?>