<?php
/////////////////////////////////////////////////////////////////////////////
// Copyright (C)2005 6XGate Incorporated
//
// This file is part of Dacomasy
//
// Dacomasy is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// Dacomasy is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
/////////////////////////////////////////////////////////////////////////////
/**
 * Contains error messages in English.
 *
 * @package Dacomasy
 * @subpackage Resources
 * @version $SixXGate: webapps/dacomasy/www/system/res/en/US/errors.inc,v 1.1.1.1 2005/07/21 22:57:33 matthew Exp $
 * @ignore
 */

$__dacomasy__ERROR_res[__DACOMASY_ERROR_SUCCESSFUL] =				'Function was Successful';

$__dacomasy__ERROR_res[__DACOMASY_ERROR_FAILAUTHCONFIG] =			'Required authentication configuration keys are missing from dacomasy.ini.';

$__dacomasy__ERROR_res[__DACOMASY_ERROR_MODULENOTVALID] =			'Module %1$s does not appear to be a valid module.';
$__dacomasy__ERROR_res[__DACOMASY_ERROR_MODULENOTFOUND] =			'Module %1$s not found.';
$__dacomasy__ERROR_res[__DACOMASY_ERROR_PANELINVALID] =				'The specified panel is invalid';

$__dacomasy__ERROR_res[__DACOMASY_ERROR_CONNECTINGTOSQLSERVER] =	'Unable to connect to the server.';
$__dacomasy__ERROR_res[__DACOMASY_ERROR_INVALIDQUERY] =				'The panel generated an invalid query.';
$__dacomasy__ERROR_res[__DACOMASY_ERROR_NOSUCHDATABASE] =			'The database %1$s does not exist.';
?>