<?php
/////////////////////////////////////////////////////////////////////////////
// Copyright (C)2005 6XGate Incorporated
//
// This file is part of Dacomasy
//
// Dacomasy is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
// 
// Dacomasy is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
/////////////////////////////////////////////////////////////////////////////
/**
 * Contains onterface labels in English.
 *
 * @package Dacomasy
 * @subpackage Resources
 * @version $SixXGate: webapps/dacomasy/www/system/res/en/US/labels.inc,v 1.1.1.1 2005/07/21 22:57:33 matthew Exp $
 * @ignore
 */

// Button Lables
$__dacomasy__LABEL_res[__DACOMASY_LABEL_OK] =						'OK';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_CANCEL] =					'Cancel';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_CHANGEPWD] =				'Change Password';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_EDIT] =						'Edit';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_DEL] =						'Delete';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_ADDNEW] =					'Add New';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_MOVEUP] =					'Move Up';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_MOVEDN] =					'Move Down';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_CLOSE] =					'Close';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_LICENSE] =					'View License...';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_YES] =						'Yes';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_NO] =						'No';

// Dialog Labels
$__dacomasy__LABEL_res[__DACOMASY_LABEL_SYSINFO] =					'System Info:';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_SERVERSW] =					'Server: ';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_SERVEROS] =					'Server OS: ';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_USERAGENT] =				'User-Agent (Client): ';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_PHPVER] =					'PHP Version ';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_MAXOF] =					'Can be no greater than %1$s characters long.';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_MINOF] =					'Must be at least %1$s characters long. ';

// Tree Headers
$__dacomasy__LABEL_res[__DACOMASY_LABEL_PANELS] =					'Modules and Panels';

// Special Headers
$__dacomasy__LABEL_res[__DACOMASY_LABEL_APPVERSION] =				'%1$s version %2$s';

// Page Headers
$__dacomasy__LABEL_res[__DACOMASY_LABEL_ABOUT] =					'About %1$s';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_ADDRECORD] =				'Add Record';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_EDITRECORD] =				'Edit Record';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_DELRECORD] =				'Delete Record';
$__dacomasy__LABEL_res[__DACOMASY_LABEL_MOVEECORD] =				'Move Record';

?>